services:
  db:
    image: postgres:16-alpine
    container_name: ${LOCAL_POSTGRES_DB:-app}-postgres
    environment:
      POSTGRES_USER: ${LOCAL_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOCAL_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOCAL_POSTGRES_DB}
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - "${LOCAL_POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${LOCAL_POSTGRES_USER} -d ${LOCAL_POSTGRES_DB}",
        ]
      interval: 2s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
